(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("ax_bar" . ("ax-plots.info" 15514 442 "Function ax_bar categories values"))
("ax_contour" . ("ax-plots.info" 17627 435 "Function ax_contour expr xvar xlo xhi yvar ylo yhi"))
("ax_draw2d" . ("ax-plots.info" 4343 378 "Function ax_draw2d [args]"))
("ax_draw3d" . ("ax-plots.info" 11065 309 "Function ax_draw3d [args]"))
("ax_heatmap" . ("ax-plots.info" 19377 481 "Function ax_heatmap z_matrix"))
("ax_histogram" . ("ax-plots.info" 21176 271 "Function ax_histogram data"))
("ax_plot2d" . ("ax-plots.info" 1583 434 "Function ax_plot2d expr [var min max]"))
("ax_polar" . ("ax-plots.info" 13538 355 "Function ax_polar expr [var min max]"))
("ax_streamline" . ("ax-plots.info" 24578 639 "Function ax_streamline Fx Fy xvar xlo xhi yvar ylo yhi"))
("ax_vector_field" . ("ax-plots.info" 22904 387 "Function ax_vector_field Fx Fy xvar xlo xhi yvar ylo yhi"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for ax-plots" . ("ax-plots.info" 981 469))
("Introduction to ax-plots" . ("ax-plots.info" 514 315))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
